### ISSUE TITLE
[setools 4.5.0] apol.css is missing from the Python package

### ISSUE THREAD

**Issue by fishilico** [SELinuxProject/setools#124]
Hello,

When upgrading to setools 4.5.0, `apol` fails:

```console
$ apol
[Errno 2] No such file or directory: '/usr/lib/python3.11/site-packages/setoolsgui/apol.css'
```

I am using Arch Linux and installing setools with a package (https://github.com/archlinuxhardened/selinux/blob/d15423e015d0ae7b9a8304f2121b09390240b26c/setools/PKGBUILD) which does:

```sh
  python setup.py build_ext
  python setup.py build
  python setup.py install --root="$pkgdir" --optimize=1 --skip-build
```

I guess this issue was caused by https://github.com/SELinuxProject/setools/pull/120 adding `setoolsgui/apol.css` while not updating `setup.py` to add CSS files to the Python package. Current setools' branch `main` contains: https://github.com/SELinuxProject/setools/blob/4c205e4153377584c7de90a8de17765bce5c52d1/setup.py#L78

Changing this line to `package_data={'': ['*.html', '*.css'],` fixed the issue for me. Would such a fix be acceptable? (Now that there is a `pyproject.toml` too, I am wondering whether this setting could be moved to this file with `[tool.setuptools] package_data = ...`)

**Comment by pebenito** [comment]
Your suggestion about adding `*.css` to the package_data sounds right to me. I'm already working on moving static config options out of `setup.py` to `pyproject.toml`, but I'd prefer to keep this fix separate so it's a trivial cherry-pick for a 4.5.1 release.
