### ISSUE TITLE
 [setools 4.5.0] networkx is not optional anymore for sesearch and seinfo

### ISSUE THREAD

**Issue by ca-hu** [SELinuxProject/setools#125]
In setools 4.4.0, the networkx dependency was made only necessary for `sedta` and `seinfoflow` (see [here](https://github.com/SELinuxProject/setools/releases/tag/4.4.2) and [here](https://github.com/SELinuxProject/setools/commit/716a1d9e1db6701c0b310dd7e10dc4a10656da0f))

The 5.6.0 update contains a refactoring, which makes the networkx dependency necessary again for other commands, such as `sesearch` and `seinfo`. This leads to issues when packaging for distributions that do not provide networkx and want to use setools in a minimal fashion.

I think it is because of this commit, which does not check if `networkx` exists: https://github.com/SELinuxProject/setools/commit/9a5ab901b1bb0cffad5ecf7895400dfc31270774

## Reproduce:
1. Remove networkx
2. Build
3. Run `sesearch` or `seinfo` command

## Result:
```
$ sesearch -A -s bin_t
Traceback (most recent call last):
  File "/usr/bin/sesearch", line 7, in <module>
    import setools
  File "/usr/lib64/python3.11/site-packages/setools/__init__.py", line 80, in <module>
    from .infoflow import *
  File "/usr/lib64/python3.11/site-packages/setools/infoflow.py", line 33, in <module>
    class InfoFlowAnalysis(DirectedGraphAnalysis):
  File "/usr/lib64/python3.11/site-packages/setools/infoflow.py", line 210, in InfoFlowAnalysis
    def graphical_results(self) -> nx.DiGraph:
                                   ^^
NameError: name 'nx' is not defined
```
## Expected Result:
```
$ sesearch -A -s bin_t
allow bin_t bin_t:dir { getattr open search };
allow bin_t bin_t:filesystem associate;
...
```

## Solution

Maybe it could be checked in the [setools/\_\_init\_\_.py](https://github.com/SELinuxProject/setools/blob/main/setools/__init__.py) if networkx is installed, and in case it is not, the sedta and seinfoflow could just not be imported.
- https://github.com/SELinuxProject/setools/blob/main/setools/__init__.py#L84
- https://github.com/SELinuxProject/setools/blob/main/setools/__init__.py#L84

Or can also be checked in the infoflow.py and sedta.py files every time it is used

**Comment by pebenito** [comment]
Please try this alternative fix: #128
