### ISSUE TITLE
Release tarballs are unsigned

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [SELinuxProject/setools#132]
Hi, could you also provide signatures of the release tarballs? As it is done e.g. for the `selinux` repository releases.

**Comment by FilippoBonazziSUSE** [comment]
What? Why would this be stale?

**Comment by ca-hu** [comment]
@pebenito would it be possible for you to sign the releases or is there anything speaking against it? we would like to verify that the releases are coming from upstream before we package them into openSUSE by checking the signatures as a precaution. 

please let us know if we are missing something here (e.g. we just did not find the signature files), thanks :)

**Comment by pebenito** [comment]
This is still valid.

**Comment by ca-hu** [comment]
still valid

**Comment by pebenito** [comment]
I added a signature to the 4.5.1 release, please try.

**Comment by FilippoBonazziSUSE** [comment]
Thanks!
