### ISSUE TITLE
TypeError:'type' object is not subscriptable"

### ISSUE THREAD

**Issue by Harlotte765** [SELinuxProject/setools#141]
When I input “python3 setup.py build_ext” ,"/usr/lib/python3/dist-packages/requests/_init_.py:89:RequestsDependencyWarning:urllib3(2.2.3)or chardet(5.2.0)doesn't match a supported version!  warning.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "Traceback (most recent call last):  File "setup.py",line13,in <module> lib_dirs:list[str]=['.','/usr/lib64','/usr/lib','/usr/local/lib;] TypeError:'type' object is not subscriptable"，May I ask how this can be resolved

**Comment by Harlotte765** [comment]
python 3.8

**Comment by pebenito** [comment]
You'll need Python 3.10 for the current release. Based on the info you provided in #142, I suggest using the setools package provided by your version of Ubuntu.
