### ISSUE TITLE
error:unknown type name 'filename_trans_key_t';did you mean 'filename trans_rule _t'

### ISSUE THREAD

**Issue by Harlotte765** [SELinuxProject/setools#142]
When I "python3 setup.py build",it find "setools/policyrep.c:4296:1:error:unknown type name 'filename_trans_key_t';did you mean 'filename trans_rule _t"

**Comment by pebenito** [comment]
What version of libsepol do you have?

**Comment by Harlotte765** [comment]
When I downloaded libsepol, it showed no matching version, so I downloaded libsepol1-dev, which is 3.0-1ubuntu0.1

**Comment by pebenito** [comment]
This is too old; you'll need libsepol 3.2 at a minimum, with 3.6+ being better.
