### ISSUE TITLE
seinfo does not expand type aliases

### ISSUE THREAD

**Issue by milosmalik** [SELinuxProject/setools#17]
https://bugzilla.redhat.com/show_bug.cgi?id=1581761

The problem still exists with setools 4.2.

**Comment by milosmalik** [comment]
sesearch from setools 4.2 suffers from the same issue:
 * https://bugzilla.redhat.com/show_bug.cgi?id=1595582

**Comment by bachradsusi** [comment]
It's being built at https://copr.fedorainfracloud.org/coprs/plautrba/setools/build/853822/ at the moment.
You try it using`dnf copr enable plautrba/setools` and `dnf update setools-console`.

In the mean time, I tried local builds and both bugs seem to be fixed:

```
> rpm -q setools-console
setools-console-4.2.1-0.0.1.fc30.x86_64

> seinfo -tspamassassin_t -x

Types: 1
   type spamc_t alias { spamassassin_t pyzor_t razor_t }, application_domain_type, nsswitch_domain, corenet_unlabeled_type, domain, kernel_system_state_reader, netlabel_peer_type, syslog_client_type, pcmcia_typeattr_1, userdom_home_manager_type;

> sesearch -t spamassassin_home_t -A | head -n 3
allow NetworkManager_ssh_t file_type:filesystem getattr;
allow NetworkManager_t file_type:filesystem getattr;
allow NetworkManager_t user_home_type:dir { getattr ioctl lock open read search };
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

The last line seems to be related to the fact that `head` closes it's stdin after 3 lines and it's no related to this issue.

**Comment by milosmalik** [comment]
python3-setools-4.2.1-0.0.1.fc28.x86_64
setools-console-4.2.1-0.0.1.fc28.x86_64
