### ISSUE TITLE
seinfo and sesearch do not recognize old boolean names

### ISSUE THREAD

**Issue by milosmalik** [SELinuxProject/setools#19]
Some booleans have been renamed in the past (for example: allow_ypbind -> nis_enabled). Various SELinux related documentation may still contain the old boolean names. To avoid confusion on sysadmin side, seinfo and sesearch should understand both old and new boolean names.

If /etc/selinux/*/booleans.subs_dist files are not supported by upstream, please close this issue.

 * https://bugzilla.redhat.com/show_bug.cgi?id=1581848
 * https://bugzilla.redhat.com/show_bug.cgi?id=1595572

**Comment by pebenito** [comment]
booleans.subs_dist is supported by upstream SELinux userspace, but not by setools. Setools is intended to operate unambiguously on the specified policy (or the loaded policy by default). Analysts may be misled by the substitution support, so this will not be implemented in setools.
