### ISSUE TITLE
Add capability to create SELinux policy

### ISSUE THREAD

**Issue by redhatrises** [SELinuxProject/setools#37]
This request is to be able to create SELinux tools graphically. The `apol` tool has most of what is needed for analyzing SELinux policies, and it seems like it wouldn't have to go far to be able to create SELinux policies and then analyze them in the same tool.

**Comment by pebenito** [comment]
This probably won't happen, as this is intended to be an analysis tool. There are no plans to do this; someone would have to step up to implement and maintain that functionality.
