### ISSUE TITLE
Update tool code to be C/C++ GUI?

### ISSUE THREAD

**Issue by redhatrises** [SELinuxProject/setools#38]
Obviously low priority, but should the tool code be updated to be a  C/C++ GUI? Python is great and all, but it means there are a lot of python dependencies that have to be maintained upstream and downstream include python version changes itself. Not to mention the fact that disconnected environments are harder to deal with, and pip needs better security handling than it has.

**Comment by pebenito** [comment]
No, this isn't a priority at all.
