### ISSUE TITLE
SETools would fail to build with next SELinux userspace release

### ISSUE THREAD

**Issue by bachradsusi** [SELinuxProject/setools#39]
SELinux Userspace is going to drop  - libsepol/include/sepol/policydb/flask.h - https://lore.kernel.org/selinux/pjdeevmzdqq.fsf@redhat.com/T/#m36e71312c34e174b84f7ad9a77f873596f7dafba Without this file, build of SETools would fail:

~~~~
running build_ext
building 'setools.policyrep' extension
creating build/temp.linux-x86_64-3.8
creating build/temp.linux-x86_64-3.8/setools
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/include/python3.8 -c setools/policyrep.c -o build/temp.linux-x86_64-3.8/setools/policyrep.o -Wextra -Waggregate-return -Wfloat-equal -Wformat -Wformat=2 -Winit-self -Wmissing-format-attribute -Wmissing-include-dirs -Wnested-externs -Wold-style-definition -Wpointer-arith -Wstrict-prototypes -Wunknown-pragmas -Wwrite-strings -Wno-unused-parameter -Wno-suggest-attribute=format -Wno-sign-compare -Wno-cast-qual -Wno-unreachable-code -Wno-implicit-fallthrough -Wno-cast-function-type -fno-exceptions
setools/policyrep.c:654:10: fatal error: sepol/policydb/flask.h: No such file or directory
  654 | #include <sepol/policydb/flask.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
~~~~

This is followup of https://github.com/SELinuxProject/selinux/pull/200#issuecomment-577745225 and the question is still valid:

> @pebenito setools currently depends on sepol/policydb/flask.h for some of these SECCLASS_ definitions, see setools/policyrep/sepol.pxd and fscontext.pxi. How hard would it be to fix it to look them up instead as in this patch?

**Comment by stephensmalley** [comment]
Any progress on this?

**Comment by pebenito** [comment]
I'm trying to square this one away, but I think there may be a bug in libsepol/checkpolicy. I'm using the F31 checkpolicy and the class values don't seem to line up. Specifically, I took the `tests/genfsconquery.conf` and added the 6 file object classes to it, and I get symbol.v.sclass having values that don't match up with the object class values. Do I need the git toolchain?

**Comment by stephensmalley** [comment]
I don't understand.  How to reproduce for someone not familiar with setools testing?

**Comment by stephensmalley** [comment]
Actually, IIUC, checkpolicy before my patch (which isn't even yet in git, just the open PR and/or patch in patchwork/lore) will use the hardcoded SECCLASS_* values in genfscon rules so that won't work without my patch.

**Comment by pebenito** [comment]
Ah, now the behavior makes sense. My setools test policies generally have fake object classes so the test policy stays simple. I had to add the file classes to the policies, so they would work without SECCLASS_* hardcoded values. This resulted in the file classes not having the same values as SECCLASS_*.

For example, here's the symbol.s.value I got from `tests/genfsconquery.conf`:
```
infoflow 1
dir 8
blk_file 14
chr_file 13
lnk_file 10
fifo_file 12
file 9
infoflow7 7
infoflow6 6
infoflow5 5
infoflow4 4
infoflow3 3
infoflow2 2
sock_file 11
```
Since the genhomedircons `symbol.v.sclass` don't line up with SECCLASS_*, I get errors. This seems like a problem for backwards compatibility, unless there is a way I can determine that the policy was compiled with the hardcoded values.

**Comment by stephensmalley** [comment]
Arguably it was already broken - with current checkpolicy without the classes defined in your policy with the same values as the hardcoded SECCLASS_* values, the genfscon entries weren't correct anyway - they were referencing class values that had nothing to do with the file-related classes.

**Comment by pebenito** [comment]
True.

With the mystery solved, I can fix up the test cases to align the object classes with SECCLASS_* values and finalize the change.
