### ISSUE TITLE
setools/policyrep/libpolicyrep.c not cleaned up with clean target

### ISSUE THREAD

**Issue by bigon** [SELinuxProject/setools#4]
Hi,

When calling the clean target, it seems that cython is building setools/policyrep/libpolicyrep.c

```
I: pybuild base:217: python3.7 setup.py clean 
Compiling setools/policyrep/libpolicyrep.pyx because it changed.
[1/1] Cythonizing setools/policyrep/libpolicyrep.pyx
running clean
[...]
```

1. setools/policyrep/libpolicyrep.c should be removed by the clean
2. Is it really necessary that cython is building files in that case?

**Comment by pebenito** [comment]
I will have to look further, but I'm not sure I can do anything about this; it may simply be a quirk of setuptools or the cython extension libraries for setuptools. The setools setup.py does not explicitly request either of these behaviors.

**Comment by pebenito** [comment]
I don't think I can do anything about the unnecessary cythonizing. From what I can tell it is a quirk of cython's distutils/setuptools support.

The clean should now work as expected.
