### ISSUE TITLE
IPv6 nodecon handling

### ISSUE THREAD

**Issue by cgzones** [SELinuxProject/setools#40]
When using a ipv6 nodecon, setools seems not handle it correctly:

After
```
git clone https://github.com/SELinuxProject/refpolicy
cd refpolicy/
echo 'network_node(lo, s0 - mls_systemhigh, 127.0.0.1, 255.255.255.255, s0 - mls_systemhigh, ::1, fe80::)' >> policy/modules/kernel/corenetwork.te.in
make conf -j
make validate -j
```

**seinfo** outputs

```
$ seinfo tmp/policy.bin --nodecon
Nodecon with network ::1 fe80:: has host bits set. Analyses may have unexpected results.

Nodecon: 2
   nodecon 127.0.0.1 255.255.255.255 system_u:object_r:lo_node_t
   nodecon :: ff00:: system_u:object_r:lo_node_t
```

**Comment by pebenito** [comment]
The warning is accurate. You're getting the unexpected results.
FE80 => 1111 111**0** 1000 0000
isn't technically a valid netmask generally speaking (I'm unsure if SELinux can actually make it work despite that), and checkpolicy/checkmodule probably shouldn't have allowed it in the first place.
