### ISSUE TITLE
when are releases of setools performed? if ad-hoc, request for a release

### ISSUE THREAD

**Issue by rc-ramillen** [SELinuxProject/setools#41]
Tried looking through the documentation of setools, but it doesn't appear to be formalized...
When are new 'release' versions of setools updated at https://github.com/SELinuxProject/setools/releases ?

Would it be possible to get a new release version that includes most of the changes to master since 4.2.1?  If no, what needs to be done or what is the trigger for new setools releases?

**Comment by pebenito** [comment]
4.3.0 released.

**Comment by rc-ramillen** [comment]
Awesome.  Thank you.
