### ISSUE TITLE
mlsvalidatetrans rule is reported as validatetrans rule

### ISSUE THREAD

**Issue by milosmalik** [SELinuxProject/setools#43]
Unfortunately, I don't know if the misinterpretation (mlsvalidatetrans vs. validatetrans) happens on the semodule side (compilation) or on the seinfo side (reporting).
```
# rpm -qa setools\*
setools-console-4.2.2-5.fc32.x86_64
# seinfo --validatetrans
Validatetrans: 0
# cat mypolicy.cil 
(mlsvalidatetrans lnk_file (neq t1 swapfile_t))
# semodule -i mypolicy.cil 
# seinfo --validatetrans
Validatetrans: 1
   validatetrans lnk_file (t1 != swapfile_t);
#
```
Tested on Fedora 32 machine where targeted policy is active.

**Comment by milosmalik** [comment]
It seems that seinfo is reporting correctly and the misinterpretation happens on semodule side:
```
# cat mypolicy.cil 
(mlsvalidatetrans file (neq t1 swapfile_t))
# semodule -i mypolicy.cil 
# checkpolicy -b -C -M -o - /sys/fs/selinux/policy | grep validatetrans
(validatetrans file (neq t1 swapfile_t))
# seinfo --validatetrans

Validatetrans: 1
   validatetrans file (t1 != swapfile_t);
#
```

**Comment by stevedlawrence** [comment]
From the perspective of the internals of selinux, there is actually no difference between validatetrans and mlsvalidatetrans (likewise for contrain and mlscontrain). They all get compiled into the same thing under the hood and the difference is lost.

When you convert a pp file or selinux policy binary file to CIL, or when seinfo reads a policy binary, we just use a heuristic to guess if a statement was mls or not. That heuristic is just if the constraint/validatetrans expression has any mls things in it. If there are no mls things, then we assume it was a validatetrans/contstraint. If there were mls things, we assumes it was a mlsvalidatetrans/mlsconstrain.

So although this may be confusing, this is behaving as expected. If you add an mls thing to your mlsvalidatetrans statement, you'll see the output becomes an mlsvalidatetrans.

**Comment by milosmalik** [comment]
Thank you for the explanation, Steve.
```
# seinfo --validatetrans

Validatetrans: 0
# cat mypolicy.cil 
(mlsvalidatetrans file (eq l1 l2))
(mlsvalidatetrans file (eq t1 t2))
# semodule -i mypolicy.cil 
# seinfo --validatetrans

Validatetrans: 2
   mlsvalidatetrans file (l1 == l2);
   validatetrans file (t1 == t2);
# 
```
This issue is not really an issue. Closing.
