### ISSUE TITLE
Do not set (runtime_)library_dirs

### ISSUE THREAD

**Issue by bigon** [SELinuxProject/setools#5]
Hi,

With the 4.2.0-beta release it seems that setools sets the RPATH (via runtime_library_dirs) to `/usr/local/lib` and `.`. In distributions like debian, this is usually discouraged, see https://wiki.debian.org/RpathIssue

Also, it seems that you are adding `/usr/local/lib` to both `runtime_library_dirs` and `library_dirs`, this is generally useless as AFAIK this is already added by default

**Comment by bigon** [comment]
`runtime_library_dirs` is definitely setting the rpath in the installed python module

**Comment by pebenito** [comment]
Ok, points taken. I was trying to avoid the LD_* environmental variable stuff, but if the runtime_library_dirs are contaminating the install, then it'll have to be done some other way.
