### ISSUE TITLE
seinfo/sestatus segfault in chroot

### ISSUE THREAD

**Issue by bigon** [SELinuxProject/setools#6]
Hi,

When testing seinfo and sesearch in a chroot, they are segfaulting:

access("/etc/selinux/targeted/policy/policy.-1", F_OK) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---

**Comment by pebenito** [comment]
Would you re-run with the `--debug` flag on seinfo or sesearch and provide output?

**Comment by bigon** [comment]
```
# seinfo --debug
2018-07-19 07:25:44,889|INFO|setools.policyrep.libpolicyrep|Attempting to locate current running policy.
Segmentation fault (core dumped)
```
```
# sesearch --debug -A 
2018-07-19 07:26:27,670|INFO|setools.policyrep.libpolicyrep|Attempting to locate current running policy.
Segmentation fault (core dumped)
```

The problem really seems that setools is not checking if `policyvers` is valid

**Comment by pebenito** [comment]
I was able to reproduce this, so you should be set.
