### ISSUE TITLE
Extremely slow since 4.2.0

### ISSUE THREAD

**Issue by bigon** [SELinuxProject/setools#7]
Hi,

It seems that sesearch is really slow (even slower than with the swig module) and uses 100% of CPU:

> $ time sesearch -AT > /dev/null 
> 
> real	1m9,680s
> user	1m9,515s
> sys	0m0,164s

seinfo is also slower and the output is not printed smoothly:

> $ time seinfo > /dev/null 
> 
> real	0m5,254s
> user	0m5,166s
> sys	0m0,088s

python 3.6
userspace 2.8

**Comment by bigon** [comment]
For comparison with version 4.1.1 on the same machine:

> $ time sesearch -AT > /dev/null 
> 
> real	0m16,883s
> user	0m16,764s
> sys	0m0,106s

> $ time seinfo  > /dev/null 
> 
> real	0m0,755s
> user	0m0,673s
> sys	0m0,082s

**Comment by pebenito** [comment]
There must have been a regression. At one point I had it at nearly half the time of 4.1.1.

**Comment by pebenito** [comment]
There's some variations, as I still can get instances where the cython is twice as fast as the swig.

cython:
```
pebenito@gentoo ~/projects/setools $ time ./sesearch -AT policy-mls.29 -s sysadm_t > /dev/null

real	0m1.883s
user	0m1.832s
sys	0m0.046s
```
swig:
```
pebenito@gentoo ~/projects/setools $ time /usr/bin/sesearch -AT policy-mls.29 -s sysadm_t > /dev/null

real	0m3.638s
user	0m3.591s
sys	0m0.045s
```

**Comment by bigon** [comment]
With cython:

> $ time sesearch -AT -s sysadm_t > /dev/null 
> 
> real	0m5,712s
> user	0m5,610s
> sys	0m0,101s

Swig:

> $ time sesearch -AT -s sysadm_t > /dev/null 
> 
> real	0m8,102s
> user	0m8,025s
> sys	0m0,076s


So indeed, when sesearch doesn't need to search in all the policy it's faster.

But it's not the case when going through everything

BTW the loaded policy is the refpolicy from git HEAD

**Comment by pebenito** [comment]
I've made some improvements. I fixed one performance regression that hit sesearch, so it's much faster for your example above:

SWIG:
```
$ time sesearch -AT policy-mls.29 > /dev/null

real	0m8.669s
user	0m8.599s
sys	0m0.062s
```
Cython before:
```
$ time ./sesearch -AT policy-mls.29 > /dev/null
 
real	0m41.594s
user	0m41.417s
sys	0m0.109s
```
Cython after:
```
$ time ./sesearch -AT policy-mls.29 > /dev/null
    
real	0m3.428s
user	0m3.358s
sys	0m0.067s
```

Seinfo is also much improved, though there is still one brief pause when it counts all the TE rules. Please try HEAD and let me know what you see. I will continue to look for ways to improve it, but I suspect it will be more difficult or require a trade-off of more memory consumption.

**Comment by bigon** [comment]
`sesearch` looks indeed faster now, thanks!
