### ISSUE TITLE
xperm range not loaded correctly if it starts with 0x00.

### ISSUE THREAD

**Issue by bauen1** [SELinuxProject/setools#74]
Adding
```
(allowx .init.type self (ioctl unix_dgram_socket (range 0x0000 0x00FF)))
```
to my policy and running sediff comparing it to the previous version yields:
```
Allowxperm Rules (0 Added, 0 Removed, 1 Modified)
   Modified Allowxperm Rules: 1
      * allowxperm init.type init.type:unix_dgram_socket ioctl { 0x8910 +0x0000 };
```

This would make you believe, that only the ioctl 0x0000 was added, when in fact it was the 0x0000 "range" or 0x0000 to 0x00FF that was added.

sediff version: 4.4.0

**Comment by pebenito** [comment]
Looks like an issue loading the ioctl values into the policyrep. I'm able to duplicate the issue, but the rule is being read with only the 0x0000 ioctl:
```
$ ./sesearch -A tests/diff_issue74_right
allow system system:infoflow3 null;
allowxperm init_type_t init_type_t:unix_dgram_socket ioctl 0x0000;
allowxperm init_type_t init_type_t:unix_dgram_socket ioctl 0x8910;
```
But the rule is as expected, as seen in dispol:
```
Command ('m' for menu):  1
allow system system : infoflow3 { null };
allowxperm init_type_t init_type_t : unix_dgram_socket ioctl { 0x8910 };
allowxperm init_type_t init_type_t : unix_dgram_socket ioctl { 0x0-0xff };
```

**Comment by pebenito** [comment]
If you change the range to 0x01-0xff it works as expected.

**Comment by bauen1** [comment]
I think that the issue is related to the optimisation of only storing 0xXX if a 0xXX00 to 0xXX+100 range is allowed.
The issue can also be shown with `0x0100` to `0x01FF`

**Comment by pebenito** [comment]
> I think that the issue is related to the optimisation of only storing 0xXX if a 0xXX00 to 0xXX+100 range is allowed. The issue can also be shown with `0x0100` to `0x01FF`

You are correct. Please try out PR #75
