### ISSUE TITLE
sepolicy compatibility

### ISSUE THREAD

**Issue by fishilico** [SELinuxProject/setools#8]
Hi,
While testing sepolicy gui with setools 4.2.0-beta, I encountered the following error:
```
  File "python/sepolicy/sepolicy/__init__.py", line 277, in _setools_rule_to_dict
    if isinstance(rule, setools.policyrep.terule.AVRule):
AttributeError: module 'setools.policyrep' has no attribute 'terule'
```

It seems that `AVRule` moved to `setools.policyrep.libpolicyrep.AVRule` (`terule` and other submodules have been merged into `libpolicyrep`), which is incompatible with sepolicy's usage of setools (cf. https://github.com/SELinuxProject/selinux/blob/selinux-python-2.8/python/sepolicy/sepolicy/__init__.py#L280).

Is this some kind of "private API" that sepolicy shouldn't use? How should sepolicy use setools?

**Comment by fishilico** [comment]
Thanks for your response. I have not got time to go back to this issue until today, sorry for this.
Your last point (about using `AttributeError` instead of internal exceptions) seems right.

I also agree about not using `setools.policyrep` and `qpol_symbol` if they are internal. They are currently used in order to get whether a rule is enabled or not. As far as I understand, `rule.conditional` refers to a condition over booleans (linked with boolean operators), and the rule is enabled only when evaluating this condition gives  `rule.conditional_block` (which is `True` or `False`).
Does `setools` provide a straightforward way of getting whether a rule is enabled or not given the state of the booleans within? If not, I will try to play with `Conditional.evaluate()` and a dict constructed from `setools.BoolQuery(pol).results()`.

**Comment by pebenito** [comment]
There isn't a direct method to determine if a rule is enabled, but I think I will add one.

**Comment by pebenito** [comment]
I added a `PolicyRule.enabled()` method in bcf97c0280385307aac2da781ad3d0c55a69d4c8. It works like the `Conditional.evaluate()`.

I also made both methods ignore extra keyword arguments, so you can simply provide a dictionary of all Boolean values, so you don't have to process the input values so much.
